server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: Config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

          
          

          
          
          
          
          
          
          
          
          
          
          
          
          
          
          